couchbase/docker

generate/resources/couchbase-server/scripts/couchbase-start, generate/templates/couchbase-server/Dockerfile.template
- use the more broad `centos:6` base so that CentOS updates are applied appropriately and transparently without a bump to the `Dockerfile`s here
- rearrange `Dockerfile` for improved cache overlap (and improved repeat cache in general)
- change the "default command" to actually be the `couchbase-server` invocation, and have the `couchbase-start` script just execute what's passed in directly, adding `gosu` appropriately if it's `couchbase-server` we're trying to run (this also allows users who enjoy the Erlang console to avoid `-noinput` by just doing `docker run -it <image> couchbase-server`)
- adjust `VOLUME` to apply to the actual mutable bits (where the data gets stored) so that recreations can be as simple as `docker stop old-container`, `docker run --volumes-from old-container --name …
=> Make a few minor tweaks

enterprise/couchbase-server/4.0.0-beta/Dockerfile
The 4.0.0-beta version was installing the wrong RPM
=> 4.0.0-beta needs to install CentOS 6 RPM not CentOS 7

community/couchbase-server/2.2.0/README.md, community/couchbase-server/3.0.1/README.md, community/couchbase-server/4.0.0/README.md, enterprise/couchbase-server/2.5.2/README.md, enterprise/couchbase-server/3.0.2/README.md, enterprise/couchbase-server/3.0.3/README.md, enterprise/couchbase-server/3.1.0/README.md, enterprise/couchbase-server/4.0.0-beta/README.md, enterprise/couchbase-server/4.0.0-dp/README.md, enterprise/couchbase-server/4.0.0-rc0/README.md, enterprise/couchbase-server/4.0.0/README.md, enterprise/couchbase-server/4.1.0/README.md, generate/resources/couchbase-server/README.md
@theprojectabot reported on gitter not being able to connect to the container from gocb.  Opening more ports fixed his issue.
=> Document more port mappings by default

community/couchbase-server/2.2.0/Dockerfile, community/couchbase-server/3.0.1/Dockerfile, community/couchbase-server/4.0.0/Dockerfile, enterprise/couchbase-server/2.5.2/Dockerfile, enterprise/couchbase-server/3.0.2/Dockerfile, enterprise/couchbase-server/3.0.3/Dockerfile, enterprise/couchbase-server/3.1.0/Dockerfile, enterprise/couchbase-server/4.0.0-beta/Dockerfile, enterprise/couchbase-server/4.0.0-dp/Dockerfile, enterprise/couchbase-server/4.0.0-rc0/Dockerfile, enterprise/couchbase-server/4.0.0/Dockerfile, enterprise/couchbase-server/4.1.0/Dockerfile, enterprise/couchbase-server/4.5.0-DP1/Dockerfile, generate/templates/couchbase-server/Dockerfile.template
As mentioned on #30 .
Please check my doc comments for accuracy; I summarized them from http://developer.couchbase.com/documentation/server/4.1/install/install-ports.html .
Anyone know if there is an SSL query port, which I assume would be at 18093?
=> Expose port 9110 for FTS. Also add comments documenting ports.

community/sync-gateway/1.2.1/Dockerfile, community/sync-gateway/1.2.1/README.md
As suggested here... https://github.com/couchbase/sync_gateway/issues/1366#issuecomment-165535857
I added config for 1.2.1. But the docker file does not work right now, I think because the 1.2.1 release has not been tagged on the sync-gateway repo.
`Step 10 : RUN mkdir -p $GOPATH &&     cd /opt &&     git clone https://github.com/couchbase/sync_gateway.git &&     cd $SGROOT &&     git checkout 1.2.1 &&     git submodule update --init --recursive &&     ./build.sh &&     cp bin/sync_gateway /usr/local/bin &&     mkdir -p $SGROOT/data
---> Running in c54bac290718
Cloning into 'sync_gateway'...
error: pathspec '1.2.1' did not match any file(s) known to git.`
=> sync-gateway community 1.2.1 docker configuration

community/couchbase-server/3.0.1/Dockerfile, community/couchbase-server/3.1.3/Dockerfile, community/couchbase-server/4.0.0/Dockerfile, community/couchbase-server/4.1.0/Dockerfile, enterprise/couchbase-server/2.5.2/Dockerfile, enterprise/couchbase-server/3.0.2/Dockerfile, enterprise/couchbase-server/3.0.3/Dockerfile, enterprise/couchbase-server/3.1.0/Dockerfile, enterprise/couchbase-server/3.1.3/Dockerfile, enterprise/couchbase-server/3.1.5/Dockerfile, enterprise/couchbase-server/3.1.6/Dockerfile, enterprise/couchbase-server/4.0.0/Dockerfile, enterprise/couchbase-server/4.1.0/Dockerfile, enterprise/couchbase-server/4.1.1/Dockerfile, enterprise/couchbase-server/4.1.2/Dockerfile, enterprise/couchbase-server/4.5.0/Dockerfile, enterprise/couchbase-server/4.5.1/Dockerfile, enterprise/couchbase-server/4.7.0/Dockerfile, enterprise/couchbase-server/4.7.0/README.md, enterprise/couchbase-server/4.7.0/scripts/dummy.sh, enterprise/couchbase-server/4.7.0/scripts/entrypoint.sh, enterprise/couchbase-server/4.7.0/scripts/run, generate/templates/couchbase-server/Dockerfile.template
This allows us to override those values for local builds, and avoids
persisting the values in the image environment unnecessarily.
Also, add a 4.7.0 directory for upcoming release.
=> Use ARG rather than ENV for build config values.

community/sync-gateway/1.4.0-2/Dockerfile, community/sync-gateway/1.4.0-2/README.md, community/sync-gateway/1.4.0-2/config/sync_gateway_config.json
This commit adds the dockerfile and supporting material generated by
generate.go for the 1.4.0-2 release of sync gateway
https://hub.docker.com/r/nkhumphreys7/docker/builds/
=> Add community sync-gateway 1.4.0-2

samples/sandbox/configure-node.sh
Also make curl statements quiet and echo basic info back to user during startup.
Use -t to give user terminal output, instead of backgrounding with -d - then they can see the status output.
=> add default bucket,  rm travel-sample

.gitattributes
Motivation
----------
If bash scripts are checked out on Windows, they'll have CR/LF line
endings by default.  If you then build a Docker image, the image will
not work because bash requires LF line endings.
Modifications
-------------
Ensure that Bash scripts in this repo always get LF line endings, even
if checked out on Windows.
Results
-------
Docker image builds for Couchbase on Linux will now work if built from a
Windows machine.
=> Ensure bash scripts have LF line endings on Windows

community/couchbase-server/5.0.0/Dockerfile, enterprise/couchbase-server/5.0.0/Dockerfile
Motivation
----------
In addition to the already exposed FTS port 8094, it can also run over
SSL using port 18094.
Modifications
-------------
Expose port 18094 in the Dockerfile for 5.0.0.
Results
-------
It is now more obvious to image users which ports may need to be mapped
for complete functionality.
=> Expose FTS SSL port 18094 for 5.0.0 couchbase-server image

README.md, community/sync-gateway/2.0.0-devbuild/Dockerfile, community/sync-gateway/2.0.0-devbuild/README.md, community/sync-gateway/2.0.0-devbuild/config/sync_gateway_config.json, generate/generator/generate.go
There's no easy way for users, internal developers, or internal developer advocates to preview upcoming releases of Sync Gateway under docker.
1. Add the ability to declare a different download url and package name for a given (unreleased) version.  See README updates on how this works from the perspective of a maintainer.
1. Currently only works in Sync Gateway, but mechanism can be re-used for couchbase server
1. Read the version customizations from a json file rather than hardcoding in the go code
=> Ability to customize download url for unreleased versions

generate/resources/couchbase-server/scripts/entrypoint.sh
When ports are specified as environment variable, they override their
default ports in the `static_config`.
So to override e.g. `rest_port`, just the environment-var `REST_PORT=1234`
must be defined. The statement is valid to say, why not doing this via 
docker port bindings. True, for rest_port this would work but for other ports
like the `query_port` it wouldn't.
=> Allow ports to be overridden

generate/resources/couchbase-server/scripts/entrypoint.sh
Earlier, it was not possible to override capi port using environment variables. So, code for overriding capi port is added to entrypoint.sh and now, its possible to override capi port.
=> updated entrypoint.sh to enable capi port overriding

enterprise/couchbase-server/6.0.1/Dockerfile, enterprise/couchbase-server/6.0.2/Dockerfile, enterprise/couchbase-server/6.0.3/Dockerfile, enterprise/couchbase-server/6.0.4/Dockerfile, enterprise/couchbase-server/6.0.5/Dockerfile, generate/generator/generate.go, generate/templates/couchbase-server/Dockerfile.template
6.0.x depended on a package (libssl1.0.0) which wasn't available by default in ubuntu:18.04. Using "apt-get" rather than "dpkg" to install is a general solution for these kinds of problems and should have been done all along.
=> CBD-4059: Use apt-get rather than dpkg to install

enterprise/couchbase-server/6.6.5/Dockerfile, generate/templates/couchbase-server/Dockerfile.template
Based on tips from the Docker team, we're now using Go templating to
include/exclude chunks of the Dockerfile based on the target distro.
Moved directory organization of runit into runit_build stage, so main
stage doesn't need to COPY and then RUN to make changes.
Cleaned up cross-distro PKG_COMMAND invocations to do (or not do) more
correct invocations of "update" and "cleanup".
Formatted multi-line && commands consistently and used "set -x" in all
cases.
=> MB-49155: Update cross-arch Dockerfile.template with best practices

enterprise/couchbase-server/7.0.3/Dockerfile, generate/generator/generate.go, generate/templates/couchbase-server/Dockerfile.template
Introduced DockerfileVariant.TargetVersion, which is the name of the
directory under enterprise/PRODUCT. This will generally be the same
as Version, but occasionally we must build the Docker image with
version X from a released product with a slightly different version.
Also simplified generateVersions() to make it easier to add in
specific exception cases.
=> CBD-4603: Tweak generation to allow building from a different version

enterprise/couchbase-server/6.5.2/Dockerfile, enterprise/couchbase-server/6.5.2/scripts/entrypoint.sh, enterprise/couchbase-server/6.5.2/scripts/run, generate/generator/generate.go, generate/templates/couchbase-server/Dockerfile.template
The systemd-ctl script in Server (which is used by the installer to
start/stop server) includes a heuristic to detect whether it is running
inside a container or not, so it knows whether to invoke systemd
commands or start/stop server manually. In Server < 7.0.0, this
heuristic was flawed and could fail in some environments, including
GitHub actions. It now appears that this could cause failures on Docker
Hub's automated builds, including security rebuilds of the Official
Image.
This change splits the install process into two parts: first unpack all
the files, then configure the package. Between those two it
monkey-patches systemd-ctl to use the newer 7.0.0+ method of detecting
whether systemd is available, rather than attempting to detect "inside a
container".
The generation will only …
=> MB-51605: Patch install process for Server < 7.0.0

generate/templates/couchbase-server/Dockerfile.template
This change:
- Adds some missing ports to our EXPOSE list
- Updates port descriptions to match [the current docs](https://docs.couchbase.com/server/current/install/install-ports.html) 
- Removes version info (which was all related to versions which are now EOL)
=> CBD-5188: Update EXPOSE ports and descriptions

generate/resources/sync-gateway/README.md, generate/templates/sync-gateway/Dockerfile.ubuntu.template
Update README to reflect the latest SGW.  I moved "Admin Port" below "Running with a Couchbase Server container" since SGW needs to be bootstrapped with couchbase server first starting from 3.0.
Switch to use startup_config/basic.json for 3.x docker images.
-Ming
=> CBD-5330, update README for SGW, change config for 3.x.

generate/templates/sync-gateway/Dockerfile.ubuntu.template
Ideally, sync gateway won't write any files here, but sometimes this happens. This behavior matches that of the systemd setup.
=> CBG-3613 run sync gateway in writeable directory

generate/generator/generate.go, generate/resources/couchbase-server/scripts/entrypoint.sh, generate/templates/couchbase-server/Dockerfile.template
runsvdir is modified to respond to TERM signals by gracefully terminating and awaiting all monitored child processes, allowing for the container to stop Server gracefully.
=> CBD-5735: Utilize our fork of runit

generate/resources/couchbase-server/scripts/run, generate/screenshots/robot/Dockerfile
Currently we attempt to chown the contents of /opt/couchbase/var without intercepting issues, which can result in chown failure messages appearing as-is on mounted volumes where ownership is not directly modifiable:
> Starting Couchbase Server -- Web UI available at http://<ip>:8091
> and logs available in /opt/couchbase/var/lib/couchbase/logs
> chown: changing ownership of 'var/lib/couchbase': Operation not permitted
This change aims to intercept such failures and provide a more informative warning, and also fixes some issues with the dockerhub screenshot generator.
=> CBD-5850: Improve warnings when failing to chown files/dirs at startup

generate/resources/couchbase-server/scripts/run
To avoid confusion on e.g. mounted volumes where the ownership of the volume cannot be modified (but the directory is writable) this change aims to replace the blanket chown approach with a test for writability when running as 'couchbase' user.
=> CBD-5850: Test contents of var are writable when running as non-root

generate/templates/sync-gateway/Dockerfile.ubuntu.template
Sync gateway writes files to this location, so this should be a volume instead of writing into the container.
=> CBG-3819 declare log file directory to be a volume

generate/generator/generate.go
python-httplib2 fails to install on ubuntu 22.04.  revert back to 20.0.4 until we sort out a solution.
-Ming
=> CBD-5977, revert to ubuntu default to 20.04 for couchbase-server and columnar

generate/generator/generate.go
Failure of python-httplib2 mentioned in https://github.com/couchbase/docker/pull/216 was due to cb-docker-tool landing on an inaccurate couchbase-server version.  This was a special use case for creating toy columnar container.  I have modified the jenkins job to use couchbase-columnar template.  It is safe to use 22.0.4 as default now.
-Ming
=> reconfigure default ubuntu version to 22.0.4 for couchbase-server and couchbase-columnar

generate/resources/couchbase-server/scripts/entrypoint.sh, generate/resources/enterprise-analytics/scripts/entrypoint.sh
This check is only performed when the file `validate-cpu-microarchitecture.sh` exists, which it will in any releases that are compiled with x86_64-v3.
=> CBD-6297: Check for x86_64-v3 at container startup
