couchbase/docker

enterprise/couchbase-server/4.0.0-beta/Dockerfile, enterprise/couchbase-server/4.0.0-beta/README.md, enterprise/couchbase-server/4.0.0-beta/scripts/couchbase-start
Note that the generated Dockerfile per https://github.com/misterbisson/couchbase-docker#regenerating-from-templates does not build successfully, so this PR includes manual changes in https://github.com/couchbase/docker/commit/f648d5702b47816d201ea6064493eb7f94beb485 to make it work.
=> Adding the Couchbase 4 beta

community/couchbase-server/2.2.0/Dockerfile, community/couchbase-server/3.0.1/Dockerfile, enterprise/couchbase-server/2.5.2/Dockerfile, enterprise/couchbase-server/3.0.2/Dockerfile, enterprise/couchbase-server/3.0.3/Dockerfile, enterprise/couchbase-server/3.1.0/Dockerfile, enterprise/couchbase-server/4.0.0-beta/Dockerfile, enterprise/couchbase-server/4.0.0-dp/Dockerfile, enterprise/couchbase-server/4.0.0-rc0/Dockerfile, generate/templates/couchbase-server/Dockerfile.template
Fix curl pursuant to https://github.com/couchbase/docker/issues/13
=> Add /opt/couchbase/lib to LD_LIBRARY_PATH to fix curl

enterprise/couchbase-server/4.1.0/Dockerfile, enterprise/couchbase-server/4.1.0/README.md, enterprise/couchbase-server/4.1.0/scripts/entrypoint.sh, enterprise/couchbase-server/4.1.0/scripts/run
=> Adds 4.1.0 for enterprise edition

enterprise/couchbase-server/3.1.5/Dockerfile, enterprise/couchbase-server/3.1.5/README.md, enterprise/couchbase-server/3.1.5/scripts/entrypoint.sh, enterprise/couchbase-server/3.1.5/scripts/run, enterprise/couchbase-server/4.1.1/Dockerfile, enterprise/couchbase-server/4.1.1/README.md, enterprise/couchbase-server/4.1.1/scripts/entrypoint.sh, enterprise/couchbase-server/4.1.1/scripts/run, enterprise/couchbase-server/4.5.0-beta/Dockerfile, enterprise/couchbase-server/4.5.0-beta/README.md, enterprise/couchbase-server/4.5.0-beta/scripts/entrypoint.sh, enterprise/couchbase-server/4.5.0-beta/scripts/run
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/docker/33)
=> Add 3.1.5, 4.1.1 and 4.5.0-beta

community/couchbase-server/2.2.0/Dockerfile, community/couchbase-server/3.0.1/Dockerfile, community/couchbase-server/3.1.3/Dockerfile, community/couchbase-server/4.0.0/Dockerfile, enterprise/couchbase-server/2.5.2/Dockerfile, enterprise/couchbase-server/3.0.2/Dockerfile, enterprise/couchbase-server/3.0.3/Dockerfile, enterprise/couchbase-server/3.1.0/Dockerfile, enterprise/couchbase-server/3.1.3/Dockerfile, enterprise/couchbase-server/3.1.5/Dockerfile, enterprise/couchbase-server/4.0.0/Dockerfile, enterprise/couchbase-server/4.1.0/Dockerfile, enterprise/couchbase-server/4.1.1/Dockerfile, enterprise/couchbase-server/4.5.0-beta/Dockerfile, generate/templates/couchbase-server/Dockerfile.template
As suggested in https://github.com/docker-library/official-images/pull/1781#issuecomment-222027739
=> Reduce COPY to reduce number of layers

community/couchbase-server/2.2.0/scripts/run, community/couchbase-server/3.0.1/scripts/run, community/couchbase-server/3.1.3/scripts/run, community/couchbase-server/4.0.0/scripts/run, community/couchbase-server/4.1.0/scripts/run, enterprise/couchbase-server/2.5.2/scripts/run, enterprise/couchbase-server/3.0.2/scripts/run, enterprise/couchbase-server/3.0.3/scripts/run, enterprise/couchbase-server/3.1.0/scripts/run, enterprise/couchbase-server/3.1.3/scripts/run, enterprise/couchbase-server/3.1.5/scripts/run, enterprise/couchbase-server/3.1.6/scripts/run, enterprise/couchbase-server/4.0.0/scripts/run, enterprise/couchbase-server/4.1.0/scripts/run, enterprise/couchbase-server/4.1.1/scripts/run, enterprise/couchbase-server/4.1.2/scripts/run, enterprise/couchbase-server/4.5.0/scripts/run, generate/resources/couchbase-server/scripts/run
Fixes #46 + https://issues.couchbase.com/browse/MB-20430
=> Fixes #46 Unexpected error in Couchbase Server logs

community/sync-gateway/1.4.1-3/Dockerfile, community/sync-gateway/1.4.1-3/README.md, community/sync-gateway/1.4.1-3/config/sync_gateway_config.json, community/sync-gateway/1.5.0-377/Dockerfile, community/sync-gateway/1.5.0-377/README.md, community/sync-gateway/1.5.0-377/config/sync_gateway_config.json, enterprise/sync-gateway/1.4.1-3/Dockerfile, enterprise/sync-gateway/1.4.1-3/README.md, enterprise/sync-gateway/1.4.1-3/config/sync_gateway_config.json, enterprise/sync-gateway/1.5.0-377/Dockerfile, enterprise/sync-gateway/1.5.0-377/README.md, enterprise/sync-gateway/1.5.0-377/config/sync_gateway_config.json
User request: https://forums.couchbase.com/t/sync-gateway-docker-repository/12971
=> Add Sync Gateway 1.4.1-3 and 1.5.0-377

community/couchbase-server/2.2.0/Dockerfile, community/couchbase-server/3.0.1/Dockerfile, community/couchbase-server/3.1.3/Dockerfile, community/couchbase-server/4.0.0/Dockerfile, community/couchbase-server/4.1.0/Dockerfile, community/couchbase-server/4.1.1/Dockerfile, community/couchbase-server/4.5.0/Dockerfile, community/couchbase-server/4.5.1/Dockerfile, enterprise/couchbase-server/2.5.2/Dockerfile, enterprise/couchbase-server/3.0.2/Dockerfile, enterprise/couchbase-server/3.0.3/Dockerfile, enterprise/couchbase-server/3.1.0/Dockerfile, enterprise/couchbase-server/3.1.3/Dockerfile, enterprise/couchbase-server/3.1.5/Dockerfile, enterprise/couchbase-server/3.1.6/Dockerfile, enterprise/couchbase-server/4.0.0/Dockerfile, enterprise/couchbase-server/4.1.0/Dockerfile, enterprise/couchbase-server/4.1.1/Dockerfile, enterprise/couchbase-server/4.1.2/Dockerfile, enterprise/couchbase-server/4.5.0/Dockerfile, enterprise/couchbase-server/4.5.1/Dockerfile, enterprise/couchbase-server/4.6.0-DP/Dockerfile, enterprise/couchbase-server/4.6.0/Dockerfile, enterprise/couchbase-server/4.6.1/Dockerfile, enterprise/couchbase-server/4.6.2/Dockerfile, enterprise/couchbase-server/4.6.3/Dockerfile, enterprise/couchbase-server/5.0.0-beta/Dockerfile, enterprise/couchbase-server/5.0.0-beta2/Dockerfile, generate/templates/couchbase-server/Dockerfile.template
Rework https://github.com/couchbase/docker/pull/80 to update template and regenerate
=> Expose full text search SSL

enterprise/sync-gateway/2.0.0-devbuild/Dockerfile, enterprise/sync-gateway/2.0.0-devbuild/README.md, enterprise/sync-gateway/2.0.0-devbuild/config/sync_gateway_config.json, generate/generator/generate.go
- Adds the SG 2.0 devbuild for the EE edition
- Bumps the devbuild # for the CE edition
=> Add SG 2.0.0 enterprise devbuild

enterprise/couchbase-operator/1.0.0/Dockerfile, enterprise/couchbase-operator/1.0.0/README.md, generate/generator/generate.go, generate/resources/couchbase-operator/README.md, generate/templates/couchbase-operator/Dockerfile.template
Update generator script to produce couchbase-operator Dockerfiles.
=> CBD-2649: Content for Official Docker Image for couchbase-operator

community/sync-gateway/2.1.3/Dockerfile, community/sync-gateway/2.1.3/README.md, community/sync-gateway/2.1.3/config/sync_gateway_config.json, community/sync-gateway/2.1.3/scripts/entrypoint.sh, enterprise/sync-gateway/2.1.3/Dockerfile, enterprise/sync-gateway/2.1.3/README.md, enterprise/sync-gateway/2.1.3/config/sync_gateway_config.json, enterprise/sync-gateway/2.1.3/scripts/entrypoint.sh
@ceejatec  verified with a docker build and docker run
=> CBD-2927 Sync Gateway 2.1.3 release

enterprise/couchbase-server/5.5.5/Dockerfile, enterprise/couchbase-server/5.5.5/README.md, enterprise/couchbase-server/5.5.5/scripts/dummy.sh, enterprise/couchbase-server/5.5.5/scripts/entrypoint.sh, enterprise/couchbase-server/5.5.5/scripts/run
=> 5.5.5 release Dockerfile

community/sync-gateway/2.5.1/Dockerfile, community/sync-gateway/2.5.1/README.md, community/sync-gateway/2.5.1/config/sync_gateway_config.json, community/sync-gateway/2.5.1/scripts/entrypoint.sh, enterprise/sync-gateway/2.5.1/Dockerfile, enterprise/sync-gateway/2.5.1/README.md, enterprise/sync-gateway/2.5.1/config/sync_gateway_config.json, enterprise/sync-gateway/2.5.1/scripts/entrypoint.sh
Verified locally with docker build and docker run
=> Sync Gateway 2.5.1 Dockerfile

generate/generator/generate.go
set packagesBaseUrl based on IsStaging.
-Ming Ho
=> CBD-3706 add staging option for SGW.

generate/generator/generate.go, generate/generator/go.mod, generate/generator/go.sum, generate/templates/couchbase-server/Dockerfile.template
MB-49155, modified docker script and template to produce both
amazonlinux and ubuntu Dockerfiles for couchbase server 7.0.3+.
-Ming Ho
=> MB-49155, modified docker script and template to produce both

generate/resources/sync-gateway/config/sync_gateway_config.json, generate/resources/sync-gateway/config/sync_gateway_config_2.x.json
per discussion with Adam and Priya, switch to use sync_gateway/examples/startup_config/basic.json.
-Ming Ho
=> CBG-1907, SGW config has changed in 3.0.0.

generate/resources/sync-gateway/README.md
- SGW readme update to reflect new config.
-Ming Ho
=> CBG-1960, readme update to reflect new config.

generate/templates/sync-gateway/Dockerfile.centos.template, generate/templates/sync-gateway/Dockerfile.ubuntu.template
use SGW's examples/serviceconfig.json as the default config so that we don't have to manually update it.
-Ming Ho
=> CBD-5174, fix SGW docker build.

generate/generator/generate.go, generate/templates/couchbase-server/Dockerfile.template
- Can "install" from a local build, rather than downloading .deb
- Can specify Server profile
Also allow overwriting Dockerfile when generating to a single output directory.
=> Add local-install and profile ability to couchbase-server Dockerfile

generate/generator/generate.go, generate/resources/couchbase-columnar/scripts/dummy.sh, generate/resources/couchbase-columnar/scripts/entrypoint.sh, generate/resources/couchbase-columnar/scripts/run, generate/templates/couchbase-columnar/Dockerfile.template
add template for generating couchbase-columnar docker images.
-Ming
=> CBD-5970 support building couchbase-columnar docker image.

generate/generator/generate.go, generate/generator/go.mod, generate/generator/go.sum
use hashicorp/go-version to compare input versions and select desired base image versions.
-Ming
=> CBD-5977, enhance ubuntuVersion.

generate/generator/generate.go, generate/resources/couchbase-edge-server/README.md, generate/templates/couchbase-edge-server/Dockerfile.template
Dockerfile template for couchbase-edge-server.
Also minor change to get columnar template truly working.
-Ming
=> CBD-6160, dockerfile template for couchbase-edge-server.

generate/templates/enterprise-analytics/Dockerfile.template
no need to configure profile.  service default is the correct one.
-Ming
=> CBD-6298, remove profile config from enterprise analytics template

generate/resources/enterprise-analytics/scripts/entrypoint.sh, generate/resources/enterprise-analytics/scripts/run, generate/templates/enterprise-analytics/Dockerfile.template
change enterprise-analytics installation location.
enterprise-analytics is now installed under /opt/enterprise-analytics
-Ming
=> CBD-6298 change enterprise-analytics installation location

generate/resources/enterprise-analytics/scripts/entrypoint.sh, generate/templates/enterprise-analytics/Dockerfile.template
- also update some logging to be EA branded
=> CBD-6400: Remove extraneous ports from being exported in EA

generate/resources/enterprise-analytics/README.md
=> Update EA README.md text to match screenshot
